class ArtPrice {
  final String image;
  final String title;
  final String artist;
  final String date;
  final double price; // Price in million dollars

  ArtPrice({
    required this.image,
    required this.title,
    required this.artist,
    required this.date,
    required this.price,
  });
}

final List<ArtPrice> artPriceLevels = [
  ArtPrice(
    image: 'assets/levels/1.png',
    title: 'Salvator Mundi',
    artist: 'Leonardo da Vinci',
    date: 'circa 1490–1500',
    price: 450.3,
  ),
  ArtPrice(
    image: 'assets/levels/2.png',
    title: 'Les Femmes d’Alger (“Version O”)',
    artist: 'Pablo Picasso',
    date: '1955',
    price: 179.4,
  ),
  ArtPrice(
    image: 'assets/levels/3.png',
    title: 'Nu couché',
    artist: 'Amedeo Modigliani',
    date: '1917–18',
    price: 170.4,
  ),
  ArtPrice(
    image: 'assets/levels/4.png',
    title: 'Nu couché (sur le côté gauche)',
    artist: 'Amedeo Modigliani',
    date: '1917–18',
    price: 157.2,
  ),
  ArtPrice(
    image: 'assets/levels/5.png',
    title: 'Three Studies of Lucian Freud',
    artist: 'Francis Bacon',
    date: '1969',
    price: 142.4,
  ),
  ArtPrice(
    image: 'assets/levels/6.png',
    title: 'Twelve Landscape Screens',
    artist: 'Qi Baishi',
    date: '1925',
    price: 140.8,
  ),
  ArtPrice(
    image: 'assets/levels/7.png',
    title: 'The Scream',
    artist: 'Edvard Munch',
    date: '1893',
    price: 119.9,
  ),
  ArtPrice(
    image: 'assets/levels/8.png',
    title: 'Young Girl with a Flower Basket',
    artist: 'Pablo Picasso',
    date: '1905',
    price: 115.0,
  ),
  ArtPrice(
    image: 'assets/levels/9.png',
    title: 'Meules',
    artist: 'Claude Monet',
    date: '1890',
    price: 110.7,
  ),
  ArtPrice(
    image: 'assets/levels/10.png',
    title: 'Untitled',
    artist: 'Jean-Michel Basquiat',
    date: '1982',
    price: 110.5,
  ),
  ArtPrice(
    image: 'assets/levels/11.png',
    title: 'Nude, Green Leaves and Bust',
    artist: 'Pablo Picasso',
    date: '1932',
    price: 106.5,
  ),
  ArtPrice(
    image: 'assets/levels/12.png',
    title: 'Silver Car Crash (Double Disaster)',
    artist: 'Andy Warhol',
    date: '1963',
    price: 105.4,
  ),
  ArtPrice(
    image: 'assets/levels/13.png',
    title: 'Garçon à la pipe',
    artist: 'Pablo Picasso',
    date: '1905',
    price: 104.2,
  ),
  ArtPrice(
    image: 'assets/levels/14.png',
    title: 'Nurse',
    artist: 'Roy Lichtenstein',
    date: '1964',
    price: 95.4,
  ),
  ArtPrice(
    image: 'assets/levels/15.png',
    title: 'Dora Maar au Chat',
    artist: 'Pablo Picasso',
    date: '1941',
    price: 95.2,
  ),
  ArtPrice(
    image: 'assets/levels/16.png',
    title: 'Chop Suey',
    artist: 'Edward Hopper',
    date: '1929',
    price: 91.9,
  ),
  ArtPrice(
    image: 'assets/levels/17.png',
    title: 'Portrait of an Artist (Pool with Two Figures)',
    artist: 'David Hockney',
    date: '1972',
    price: 90.3,
  ),
  ArtPrice(
    image: 'assets/levels/18.png',
    title: 'Orange, Red, Yellow',
    artist: 'Mark Rothko',
    date: '1961',
    price: 86.9,
  ),
  ArtPrice(
    image: 'assets/levels/19.png',
    title: 'Triptych',
    artist: 'Francis Bacon',
    date: '1976',
    price: 86.3,
  ),
  ArtPrice(
    image: 'assets/levels/20.png',
    title: 'Suprematist Composition',
    artist: 'Kazimir Malevich',
    date: '1916',
    price: 85.8,
  ),
  ArtPrice(
    image: 'assets/levels/21.png',
    title: 'Nymphéas en fleur',
    artist: 'Claude Monet',
    date: 'circa 1914–1917',
    price: 84.7,
  ),
  ArtPrice(
    image: 'assets/levels/22.png',
    title: 'Black Fire I',
    artist: 'Barnett Newman',
    date: '1961',
    price: 84.2,
  ),
  ArtPrice(
    image: 'assets/levels/23.png',
    title: 'Portrait of Dr. Gachet',
    artist: 'Vincent van Gogh',
    date: '1890',
    price: 82.5,
  ),
  ArtPrice(
    image: 'assets/levels/24.png',
    title: 'Triple Elvis',
    artist: 'Andy Warhol',
    date: '1963',
    price: 81.9,
  ),
  ArtPrice(
    image: 'assets/levels/25.png',
    title: 'No. 10',
    artist: 'Mark Rothko',
    date: '1958',
    price: 81.9,
  ),
  ArtPrice(
    image: 'assets/levels/26.png',
    title: 'Meule',
    artist: 'Claude Monet',
    date: '1890',
    price: 81.4,
  ),
  ArtPrice(
    image: 'assets/levels/27.png',
    title: 'Laboureur dans un champ',
    artist: 'Vincent van Gogh',
    date: 'circa 1889–1890',
    price: 81.3,
  ),
  ArtPrice(
    image: 'assets/levels/28.png',
    title: 'Odalisque couchée aux magnolias',
    artist: 'Henri Matisse',
    date: '1923',
    price: 80.8,
  ),
  ArtPrice(
    image: 'assets/levels/29.png',
    title: 'Three Studies for a Portrait of John Edwards',
    artist: 'Francis Bacon',
    date: '1980',
    price: 80.8,
  ),
  ArtPrice(
    image: 'assets/levels/30.png',
    title: 'Le Bassin aux Nymphéas',
    artist: 'Claude Monet',
    date: '1919',
    price: 80.5,
  ),
  ArtPrice(
    image: 'assets/levels/31.png',
    title: 'Au Moulin de la Galette',
    artist: 'Pierre-Auguste Renoir',
    date: '1876',
    price: 78.1,
  ),
];
